/* Mikoshi Gear — shared product catalog data (generated by build_showcase.py).
   Drive: product.html galleries + card live-thumbnails via catalog_media table.
   Fallback: image list here (initial/static order) when Supabase is unreachable. */
window.MIKOSHI_PRODUCTS = {
 "ins-style": {
  "name": "Ins Style Aesthetic Case (Korean / Japanese)",
  "cat": "case",
  "price": "Wholesale $3.50 \u00b7 MOQ 20 \u2014 samples available",
  "notes": "iPhone 11\u201317 \u00b7 TPU+PC soft-hard hybrid \u00b7 full coverage \u00b7 raised camera bezel \u00b7 anti-dirt \u00b7 pink shown"
 },
 "candy-double-mag": {
  "name": "Candy Double-Layer Magnetic Case",
  "cat": "case",
  "price": "Wholesale $3.50 \u00b7 MOQ 20 \u2014 samples available",
  "notes": "iPhone 11\u201317 \u00b7 shockproof TPU+PC \u00b7 transparent matte \u00b7 MagSafe \u00b7 6 colours: pink\u00b7sage\u00b7grey\u00b7sky\u00b7mint\u00b7cream"
 },
 "ultra-thin-contrast": {
  "name": "Ultra-Thin Contrast Magnetic Case",
  "cat": "case",
  "price": "Wholesale $4.00 \u00b7 MOQ 20 \u2014 samples available",
  "notes": "iPhone 13\u201318 (Pro/Pro Max/17 Air) \u00b7 ultra-thin matte \u00b7 orange accent ring \u00b7 MagSafe \u00b7 3 colours"
 },
 "slim-heat": {
  "name": "Slim Solid-Color Heat-Dissipating Case",
  "cat": "case",
  "price": "Wholesale $4.40 \u00b7 MOQ 20 \u2014 samples available",
  "notes": "iPhone 13\u201317 \u00b7 ultra-slim matte hard-shell \u00b7 heat-dissipation ring \u00b7 scratch-resistant \u00b7 cream shown"
 },
 "charming-eye": {
  "name": "Skin-Feel 'Charming Eye' Case",
  "cat": "case",
  "price": "Wholesale $4.10 \u00b7 MOQ 20 \u2014 samples available",
  "notes": "iPhone 11\u201317 + XR/XS/XS Max \u00b7 matte skin-feel \u00b7 eye graphic \u00b7 metallic accent ring \u00b7 3 colours"
 },
 "shockproof-matte-luxury": {
  "name": "Shockproof Matte Luxury Case",
  "cat": "case",
  "price": "Wholesale $3.50 \u00b7 MOQ 20 \u2014 samples available",
  "notes": "iPhone 17/16/15/14/13/12/11 Pro Max/XS/7/8 Plus/SE \u00b7 PC shockproof + waterproof \u00b7 electroplate colour frame \u00b7 translucent matte back \u00b7 5 colours"
 },
 "xframe-aluminum": {
  "name": "Aluminum X-Frame Bare Case",
  "cat": "case",
  "price": "Wholesale $20.00 \u00b7 MOQ 20 \u2014 samples available",
  "notes": "iPhone 13\u201317 Pro Max \u00b7 aluminium alloy exoskeleton \u00b7 X-back structural frame \u00b7 bezel-less bare design \u00b7 open back for air cooling \u00b7 5 colours: gold\u00b7silver\u00b7orange\u00b7grey\u00b7blue"
 },
 "2in1-wireless": {
  "name": "2-in-1 100W + Wireless Cable",
  "cat": "cable",
  "price": "Wholesale $12.50 \u00b7 MOQ 20 \u2014 samples available",
  "notes": "USB-C 100W + 2.5W wireless puck (watch/earbuds) \u00b7 E-Marker \u00b7 braided \u00b7 ships by Oct 14"
 },
 "240w-display": {
  "name": "240W Display Cable (live wattage)",
  "cat": "cable",
  "price": "Wholesale $4.00\u20138.00 \u00b7 MOQ 20 \u2014 samples available",
  "notes": "USB-C \u00b7 real-time W readout \u00b7 braided + metal housing \u00b7 480Mbps \u00b7 1/2m \u00b7 ships by Oct 14"
 },
 "240w-elbow": {
  "name": "240W Elbow 90\u00b0 Cable",
  "cat": "cable",
  "price": "Wholesale $7.00 \u00b7 MOQ 20 \u2014 samples available",
  "notes": "USB-C \u00b7 L-shaped elbow \u00b7 zinc-alloy shell \u00b7 braided nylon \u00b7 1.5m"
 },
 "240w-straight": {
  "name": "240W Max Cable",
  "cat": "cable",
  "price": "Wholesale $7.00 \u00b7 MOQ 20 \u2014 samples available",
  "notes": "USB-C \u00b7 zinc-alloy shell \u00b7 reinforced strain relief \u00b7 braided \u00b7 1.5m"
 },
 "100w-realcore": {
  "name": "100W Real-Core Cable",
  "cat": "cable",
  "price": "Wholesale $3.00\u20135.50 \u00b7 MOQ 20 \u2014 samples available",
  "notes": "USB-C \u00b7 six-strand core \u00b7 anti-interference \u00b7 gold-plated \u00b7 4 colours"
 },
 "6a-multilength": {
  "name": "6A Multi-Length Cable",
  "cat": "cable",
  "price": "Wholesale $3.00\u20134.50 \u00b7 MOQ 20 \u2014 samples available",
  "notes": "USB-C \u00b7 TPE jacket \u00b7 6A fast charge \u00b7 0.25\u20133m lengths"
 },
 "spring-cable": {
  "name": "Spring 6A Digital Cable",
  "cat": "cable",
  "price": "Wholesale $5.50 \u00b7 MOQ 20 \u2014 samples available",
  "notes": "USB-C \u00b7 1.8m stretchable coil \u00b7 braided+TPE \u00b7 pure copper \u00b7 ships by Oct 14 \u00b7 2 colours"
 },
 "3in1": {
  "name": "3-in-1 Multi-Interface Cable",
  "cat": "cable",
  "price": "Wholesale $2.50 \u00b7 MOQ 20 \u2014 samples available",
  "notes": "USB-C \u2192 Lightning + USB-C + Micro \u00b7 braided nylon \u00b7 legacy coverage \u00b7 0.6\u20131.5m"
 },
 "a2c-braided": {
  "name": "Braided A\u2192C Cable",
  "cat": "cable",
  "price": "Wholesale $3.00\u20135.00 \u00b7 MOQ 20 \u2014 samples available",
  "notes": "USB-A \u2192 USB-C \u00b7 knurled metal housing \u00b7 cable tie \u00b7 4 colours \u00b7 1\u20133m"
 },
 "otg-adapter": {
  "name": "Smart Visual PD Adapter",
  "cat": "adapter",
  "price": "Wholesale $3.50 \u00b7 MOQ 20 \u2014 samples available",
  "notes": "USB-C passthrough + live wattage display \u00b7 100W PD \u00b7 480Mbps \u00b7 car/travel \u00b7 ships by Oct 14"
 },
 "arc-lighter": {
  "name": "USB-C Arc Lighter (XG01)",
  "cat": "novelty",
  "price": "Wholesale $6.50 \u00b7 MOQ 20 \u2014 samples available",
  "notes": "Windproof plasma arc \u00b7 aluminium alloy \u00b7 8g \u00b7 long-press safety \u00b7 ships by Oct 17"
 }
};
window.MIKOSHI_IMAGES = {
 "ins-style": [
  "https://mikoshigear.ca/mikoshi-img/detail/ins-style/img-01.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/ins-style/img-02.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/ins-style/img-03.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/ins-style/img-04.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/ins-style/img-05.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/ins-style/img-06.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/ins-style/img-07.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/ins-style/img-08.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/ins-style/img-09.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/ins-style/img-10.jpg"
 ],
 "candy-double-mag": [
  "https://mikoshigear.ca/mikoshi-img/detail/candy-double-mag/img-01.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/candy-double-mag/img-02.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/candy-double-mag/img-03.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/candy-double-mag/img-04.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/candy-double-mag/img-05.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/candy-double-mag/img-06.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/candy-double-mag/img-07.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/candy-double-mag/img-08.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/candy-double-mag/img-09.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/candy-double-mag/img-10.jpg"
 ],
 "ultra-thin-contrast": [
  "https://mikoshigear.ca/mikoshi-img/detail/ultra-thin-contrast/img-01.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/ultra-thin-contrast/img-02.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/ultra-thin-contrast/img-03.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/ultra-thin-contrast/img-04.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/ultra-thin-contrast/img-05.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/ultra-thin-contrast/img-06.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/ultra-thin-contrast/img-07.jpg"
 ],
 "slim-heat": [
  "https://mikoshigear.ca/mikoshi-img/detail/slim-heat/img-01.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/slim-heat/img-02.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/slim-heat/img-03.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/slim-heat/img-04.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/slim-heat/img-05.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/slim-heat/img-06.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/slim-heat/img-07.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/slim-heat/img-08.jpg"
 ],
 "charming-eye": [
  "https://mikoshigear.ca/mikoshi-img/detail/charming-eye/img-01.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/charming-eye/img-02.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/charming-eye/img-03.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/charming-eye/img-04.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/charming-eye/img-05.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/charming-eye/img-06.jpg"
 ],
 "shockproof-matte-luxury": [
  "https://mikoshigear.ca/mikoshi-img/detail/shockproof-matte-luxury/img-01.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/shockproof-matte-luxury/img-02.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/shockproof-matte-luxury/img-03.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/shockproof-matte-luxury/img-04.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/shockproof-matte-luxury/img-05.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/shockproof-matte-luxury/img-06.jpg"
 ],
 "xframe-aluminum": [
  "https://mikoshigear.ca/mikoshi-img/detail/xframe-aluminum/img-01.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/xframe-aluminum/img-02.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/xframe-aluminum/img-03.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/xframe-aluminum/img-04.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/xframe-aluminum/img-05.jpg"
 ],
 "2in1-wireless": [
  "https://mikoshigear.ca/mikoshi-img/detail/2in1-wireless/img-01.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/2in1-wireless/img-02.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/2in1-wireless/img-03.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/2in1-wireless/img-04.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/2in1-wireless/img-05.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/2in1-wireless/img-06.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/2in1-wireless/img-07.jpg"
 ],
 "240w-display": [
  "https://mikoshigear.ca/mikoshi-img/detail/240w-display/img-01.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/240w-display/img-02.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/240w-display/img-03.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/240w-display/img-04.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/240w-display/img-05.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/240w-display/img-06.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/240w-display/img-07.jpg"
 ],
 "240w-elbow": [
  "https://mikoshigear.ca/mikoshi-img/detail/240w-elbow/img-01.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/240w-elbow/img-02.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/240w-elbow/img-03.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/240w-elbow/img-04.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/240w-elbow/img-05.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/240w-elbow/img-06.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/240w-elbow/img-07.jpg"
 ],
 "240w-straight": [
  "https://mikoshigear.ca/mikoshi-img/detail/240w-straight/img-01.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/240w-straight/img-02.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/240w-straight/img-03.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/240w-straight/img-04.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/240w-straight/img-05.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/240w-straight/img-06.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/240w-straight/img-07.jpg"
 ],
 "100w-realcore": [
  "https://mikoshigear.ca/mikoshi-img/detail/100w-realcore/img-01.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/100w-realcore/img-02.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/100w-realcore/img-03.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/100w-realcore/img-04.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/100w-realcore/img-05.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/100w-realcore/img-06.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/100w-realcore/img-07.jpg"
 ],
 "6a-multilength": [],
 "spring-cable": [
  "https://mikoshigear.ca/mikoshi-img/detail/spring-cable/img-01.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/spring-cable/img-02.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/spring-cable/img-03.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/spring-cable/img-04.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/spring-cable/img-05.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/spring-cable/img-06.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/spring-cable/img-07.jpg"
 ],
 "3in1": [
  "https://mikoshigear.ca/mikoshi-img/detail/3in1/img-01.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/3in1/img-02.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/3in1/img-03.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/3in1/img-04.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/3in1/img-05.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/3in1/img-06.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/3in1/img-07.jpg"
 ],
 "a2c-braided": [
  "https://mikoshigear.ca/mikoshi-img/detail/a2c-braided/img-01.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/a2c-braided/img-02.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/a2c-braided/img-03.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/a2c-braided/img-04.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/a2c-braided/img-05.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/a2c-braided/img-06.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/a2c-braided/img-07.jpg"
 ],
 "otg-adapter": [
  "https://mikoshigear.ca/mikoshi-img/detail/otg-adapter/img-01.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/otg-adapter/img-02.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/otg-adapter/img-03.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/otg-adapter/img-04.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/otg-adapter/img-05.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/otg-adapter/img-06.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/otg-adapter/img-07.jpg"
 ],
 "arc-lighter": [
  "https://mikoshigear.ca/mikoshi-img/detail/arc-lighter/img-01.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/arc-lighter/img-02.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/arc-lighter/img-03.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/arc-lighter/img-04.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/arc-lighter/img-05.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/arc-lighter/img-06.jpg",
  "https://mikoshigear.ca/mikoshi-img/detail/arc-lighter/img-07.jpg"
 ]
};
